services:
  frontend:
    image: registry.floxsite.de/cats-frontend:latest
    restart: always
    networks:
      - FloxNet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cats.rule=Host(`cats.floxsite.de`)"
      - "traefik.http.routers.cats.entrypoints=websecure"
      - "traefik.http.routers.cats.tls.certresolver=letsencrypt"
      - "traefik.http.services.cats.loadbalancer.server.port=8080"

  backend:
    image: registry.floxsite.de/cats-backend:latest
    restart: always
    env_file:
      - .env
    networks:
      - FloxNet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cats-api.rule=Host(`cats.floxsite.de`) && PathPrefix(`/api`)"
      - "traefik.http.routers.cats-api.entrypoints=websecure"
      - "traefik.http.routers.cats-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.cats-api.loadbalancer.server.port=5000"

networks:
  FloxNet:
    external: true
