services:
  backend:
    build:
      context: ../../KodzenLog/api
      dockerfile: Dockerfile
    ports:
      - "7777:5000"
    networks:
      - cat-network
  frontend:
    build:
      context: ../../KodzenLog/frontend
      dockerfile: Dockerfile
    ports:
      - "4543:8080"
    depends_on:
      - backend
    networks:
      - cat-network

networks:
  cat-network:
    driver: bridge
