services:
  backend:
    image: "registry.floxsite.de/cats-backend:latest"
    env_file:
      - ./.env
    ports:
      - "7777:5000"
    networks:
      - cat-network
  frontend:
    image: "registry.floxsite.de/cats-frontend:latest"
    ports:
      - "4543:8080"
    depends_on:
      - backend
    networks:
      - cat-network

networks:
  cat-network:
    driver: bridge
