entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: mail@floxsite.de
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

