services:
  app:
    image: registry.floxsite.de/hv-bingerschlag:latest
    restart: always
    env_file:
      - .env
    networks:
      - FloxNet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hv.rule=Host(`bar.floxsite.de`) || Host(`www.bar.floxsite.de`)"
      - "traefik.http.routers.hv.entrypoints=websecure"
      - "traefik.http.routers.hv.tls.certresolver=letsencrypt"
      - "traefik.http.services.hv.loadbalancer.server.port=3000"

networks:
  FloxNet:
    external: true
