services:
  db:
    image: mariadb:11
    container_name: nextcloud-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - FloxNet

  app:
    image: nextcloud:apache
    container_name: nextcloud-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.floxsite.de`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    networks:
      - FloxNet

volumes:
  db_data:
  nextcloud_data: # (optional, könntest auch bind-mount nutzen)

networks:
  FloxNet:
    external: true

