services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    networks:
      - FloxNet
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "${WEBPASSWORD}"
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.floxsite.de`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  FloxNet:
    external: true
